#!/usr/bin/env python3
"""Derives the key times (K) for every visual from the measured word times in out/vo.json.
Writes film/zeiten.js (for the film) and out/zeiten.json (for ton/partitur.py)."""
import json
j = json.load(open('out/vo.json', encoding='utf-8'))
W = j['words']
def wort(w, n=1, dt=0.0):  # start of the n-th occurrence of a script word
    hits = [x for x in W if x['w'] == w]
    return round(hits[n - 1]['start'] + dt, 3)
def ende(w, n=1):
    hits = [x for x in W if x['w'] == w]
    return round(hits[n - 1]['end'], 3)
def zeile(i, dt=0.0): return round(j['lines'][i]['start'] + dt, 3)
K = dict(
    diesel=wort('diesel'), record=wort('record'),
    now=zeile(1), china1=wort('china'), paused=wort('paused'), exports1=wort('exports'),
    refiners=wort('refiners'), stopped=wort('stopped'), abroad=wort('abroad'), october1=wort('october'),
    stocks0=zeile(3), stocks=wort('stocks'), low=wort('low'),
    world=zeile(4), short=wort('short'),
    war=zeile(5), middle=wort('middle'),
    russia=wort('russia'), holding=wort('holding'),
    diesel3=zeile(7), food=wort('food'), everything=wort('everything'),
    trucks=wort('trucks'), ships=wort('ships'), tractors=wort('tractors'),
    take0=zeile(9), take=wort('take'), china3=wort('china', 3), reach=wort('reach'),
    pool0=zeile(10), pool=wort('pool'),
    seller=wort('seller'), steps=wort('steps'), everyone=wort('everyone'), bids=wort('bids'), rest=wort('rest'),
    watch=zeile(12), october2=wort('october', 2), seventh=wort('seventh'), holiday=wort('holiday'),
    nobody=wort('nobody'), restart=wort('restart'),
    pump=wort('pump'), groceries=wort('groceries'), notice=wort('notice'), first=wort('first'), vo_end=ende('first'))
DUR = round(j['duration'] + 0.9, 2)
open('film/zeiten.js', 'w').write(f'// generated by zeiten.py from out/vo.json ({j["stimme"]})\nconst K = {json.dumps(K)};\nconst DUR = {DUR};\n')
json.dump({'K': K, 'DUR': DUR}, open('out/zeiten.json', 'w'), indent=1)
print(DUR, json.dumps(K))
