#!/usr/bin/env python3
"""Derives the key times (K) for every visual from the measured word times in out/vo.json.
Writes film/zeiten.js (for the film) and out/zeiten.json (for ton/partitur.py)."""
import json
j = json.load(open('out/vo.json', encoding='utf-8'))
W = j['words']
def wort(w, n=1, dt=0.0):
    hits = [x for x in W if x['w'] == w]
    return round(hits[n - 1]['start'] + dt, 3)
def ende(w, n=1):
    hits = [x for x in W if x['w'] == w]
    return round(hits[n - 1]['end'], 3)
def zeile(i, dt=0.0): return round(j['lines'][i]['start'] + dt, 3)
K = dict(
    google=wort('google'), chips1=wort('chips'), orbit1=wort('orbit'),
    reason=zeile(1), power1=wort('power'),
    test=wort('test'), data=wort('data'), space=wort('space'), satellite=wort('satellite'), four=wort('four'), chips2=wort('chips', 2),
    orbit2=wort('orbit', 2), sun=wort('sun'), never=wort('never'),
    panels=wort('panels'), eight=wort('eight'), power2=wort('power', 2), earth=wort('earth'),
    catch=wort('catch'), heat=wort('heat'),
    air=wort('air'), carry=wort('carry'), fifteen=wort('fifteen'), minutes=wort('minutes'), rest=wort('rest'),
    expect1=wort('expect'), startup=wort('startup'), ran=wort('ran'), own1=wort('own'), there=wort('there', 2),
    take=wort('take'), genius1=wort('genius'), idea=wort('idea'), insane1=wort('insane'), timeline=wort('timeline'),
    project=wort('project'), npr=wort('npr'), cheaper=wort('cheaper'), five=wort('five'), years=wort('years'),
    so2=zeile(10), genius2=wort('genius', 2), insane2=wort('insane', 2), vo_end=ende('insane', 2))
DUR = round(K['vo_end'] + 0.45, 2)
open('film/zeiten.js', 'w').write(f'// generated by zeiten.py from out/vo.json ({j["stimme"]})\nconst K = {json.dumps(K)};\nconst DUR = {DUR};\n')
json.dump({'K': K, 'DUR': DUR}, open('out/zeiten.json', 'w'), indent=1)
print(DUR, json.dumps(K))
